{% macro enriched_ads_base_col_select_macro(round_digits) %}
    s.location,
    s.title,
    s.link,
    s.flat_type,
    s.floor,
    s.size,
    s.price,
    s.first_price,
    s.current_price,
    s.num_seen,
    round((s.price/s.size)::numeric, {{round_digits}}) as price_m2,
    round(a.area_average::numeric, {{round_digits}}) as area_price_m2,
    round((100 * (a.area_average - s.price/s.size) / a.area_average)::numeric, 1) as area_discount,
    round(a2.area_average::numeric, {{round_digits}}) as area_sized_price_m2,
    round((100 * (a2.area_average - s.price/s.size) / a2.area_average)::numeric, 1) as area_sized_discount,
    round(a3.area_average::numeric, {{round_digits}}) as area_aged_sized_price_m2,
    round((100 * (a3.area_average - s.price/s.size) / a3.area_average)::numeric, 1)  as area_aged_sized_discount,
    round(((s.first_price - s.price)/s.first_price * 100)::numeric, 1)  as price_drop_pecentage,
    s.first_seen,
    s.last_seen,
    s.ad_id,
    s.latest_seen_date,
    s.status,
    s.days_on_the_market,
    s.price_3,
    s.price_7,
    s.price_15,
    s.price_30,
    s.price_45,
    s.price_60,
    sd.url,
    sd.location2,
    sd.street,
    sd.num_views,
    sd.advertiser,
    sd.number_of_floors,
    sd.year_built,
    sd.year_last_renovated,
    sd.total_liveable_area,
    sd.net_area,
    sd.number_of_rooms,
    sd.number_of_parking_spots,
    sd.balcony_terrace,
    case when RIGHT(sd.floor, 1) like '.'
        then SUBSTR(sd.floor, 1, LENGTH(sd.floor)-1)
        else sd.floor
    end as floor_desc,
    sd.furbishment_state,
    sd.epc_rating,
    sd.table_data,
    sd.description,
    sd.extra_description,
    sd.seen_time,
{% endmacro %}
